### PR TITLE
Properly traverse back to the App object for selecting menu items on cocoa

### LINKED ISSUE #409: Menu items broken on Cocoa backend: fails with object has no attribute '_menu_items'
I believe this is a regression from 1d41d3833eb4b8785faf8eb7850f3feec4650350 / #373. The changes `appDelegate.interface` from the `App` instance to `App.interface`. Unfortunately, selecting a menu item still expects `appDelegate.interface` to be the `App` instance, see below where it calls `self.interface._menu_items`:

https://github.com/pybee/toga/blob/ad91f1a65a109b670256028e31c887dc18a4876d/src/cocoa/toga_cocoa/app.py#L71-L75

## Expected Behavior
The action successfully runs.

## Current Behavior
The action doesn't run, you get an error in the terminal:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/pcloke/.virtualenvs/toga/lib/python3.6/site-packages/rubicon/objc/runtime.py", line 1033, in _objc_method
    result = f(py_self, *args)
  File "/Users/pcloke/toga/src/cocoa/toga_cocoa/app.py", line 73, in selectMenuItem_
    cmd = self.interface._menu_items[sender]
AttributeError: 'TogaDemo' object has no attribute '_menu_items'
```

## Steps to reproduce

1. Run the toga demo app (`cd toga && python -m toga_demo`)
2. Click on one of the "Commands" > "Action 1"

## Your Environment

* Python 3.6.
* macOS High Sierra
* Toga Target: cocoa

### PR DESCRIPTION
**Pull request by clokep**
Properly call back to the `App` object to get access to `_menu_items` to run menu commands.

Fixes #409 

## PR Checklist:
- [ ] All new features have been tested
- [ ] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Comment by clokep** [comment]
I can add a test for this, let me know if I should poke into those.

**Comment by freakboy3742** [comment]
@clokep If you can work up a test case for this, that would be great; if it can't be tested easily, drop a comment to that effect and I'll merge as-is.

**Comment by clokep** [comment]
I'm fairly sure this can be tested, but I'm having some trouble wrapping my mind around it. I think you'd need to create a sample `toga.App` with a `Command` on it, but I'm unsure if that test will "work" without an event loop / UI showing.

**Comment by clokep** [comment]
@freakboy3742 Just wanted to close the loop on here -- I'm not sure I'll get another chance to look at this for a couple of weeks. So it might be better to merge this as is instead of waiting for the tests. Your call though!

Thanks for all your hard work! 🥇

**Comment by clokep** [comment]
Thanks!
