### ISSUE TITLE
Toga not working from pip install with latest colosseum

### ISSUE THREAD

**Issue by imrosca** [pybee/toga#120]
```
$ pip freeze
appdirs==1.4.3
colosseum==0.1.4
Django==1.10.6
packaging==16.8
pyparsing==2.2.0
rrdtool==0.1.11
six==1.10.0
toga==0.2.4
toga-core==0.2.4
toga-demo==0.2.4
toga-gtk==0.2.4
$ toga-demo                                                                                                          
Traceback (most recent call last):                                                                                                                    
  File "/.../bin/toga-demo", line 7, in <module>                                                                              
    from toga_demo.__main__ import main                                                                                                               
  File "/.../lib/python3.6/site-packages/toga_demo/__main__.py", line 6, in <module>                                          
    from .app import TogaDemo                                                                                                                         
  File "/.../lib/python3.6/site-packages/toga_demo/app.py", line 4, in <module>                                               
    import toga
  File "/.../lib/python3.6/site-packages/toga/__init__.py", line 9, in <module>
    import toga.interface.app  # NOQA
  File "/.../lib/python3.6/site-packages/toga/interface/__init__.py", line 6, in <module>
    from .widgets.box import *
  File "/.../lib/python3.6/site-packages/toga/interface/widgets/box.py", line 1, in <module>
    from .base import Widget
  File "/.../lib/python3.6/site-packages/toga/interface/widgets/base.py", line 1, in <module>
    from colosseum import CSSNode
ImportError: cannot import name 'CSSNode'
```
I think it's this change that fixes it:
https://github.com/pybee/toga/commit/fd5ca618392b566f0094c0ddf36eb45f0ebef6c4#diff-58145867ab01b00b7681073879b17d0bL2

I pip installed toga first, then toga-demo in a python 3.6 virtualenv.

It works fine with colosseum 0.1.3 btw 👍

**Comment by freakboy3742** [comment]
Thanks for the report - there have been some recent changes to Colosseum that have been reflected in the Toga codebase. Colosseum has had a 0.1.4 release, but Toga hasn't been updated.

I'm expecting to push out a new Toga release very shortly, that should address this problem. In the interim, if you install directly from Git (rather than from PyPI), toga-demo should work.

Apologies for the inconvenience.

**Comment by imrosca** [comment]
Not inconvenienced at all, just letting you know in case you thought a quick fix was worth it - good to know there's a toga release imminent.

**Comment by Myextraordinarylife** [comment]
[helloworld] Starting in dev mode...
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/abdulsamedwalker/beeware-tutorial/helloworld/src/helloworld/__main__.py", line 1, in <module>
    from helloworld.app import main
ImportError: cannot import name 'main' from 'helloworld.app' (/Users/abdulsamedwalker/beeware-tutorial/helloworld/src/helloworld/app.py)

**Comment by Myextraordinarylife** [comment]
am getting an error when i want to run briefcase dev

**Comment by freakboy3742** [comment]
@Myextraordinarylife It's not clear why you've attached your report to this ticket. You appear to be reporting a problem with briefcase, not toga; and there's no obvious connection to Colosseum (the subject of this ticket). You also haven't shared any details about what you've done, and how you got to this situation (the reference to `runpy.py`, for example, suggests you *haven't* followed the instructions in the Briefcase tutorial regarding virtual environments)

Can I suggest that you [open a ticket on the *briefcase* repository](https://github.com/beeware/briefcase/issues/new), with *full* details of what you've done?
