### ISSUE TITLE
Menu items broken on Cocoa backend: fails with object has no attribute '_menu_items'

### ISSUE THREAD

**Issue by clokep** [pybee/toga#409]
I believe this is a regression from 1d41d3833eb4b8785faf8eb7850f3feec4650350 / #373. The changes `appDelegate.interface` from the `App` instance to `App.interface`. Unfortunately, selecting a menu item still expects `appDelegate.interface` to be the `App` instance, see below where it calls `self.interface._menu_items`:

https://github.com/pybee/toga/blob/ad91f1a65a109b670256028e31c887dc18a4876d/src/cocoa/toga_cocoa/app.py#L71-L75

## Expected Behavior
The action successfully runs.

## Current Behavior
The action doesn't run, you get an error in the terminal:

```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/Users/pcloke/.virtualenvs/toga/lib/python3.6/site-packages/rubicon/objc/runtime.py", line 1033, in _objc_method
    result = f(py_self, *args)
  File "/Users/pcloke/toga/src/cocoa/toga_cocoa/app.py", line 73, in selectMenuItem_
    cmd = self.interface._menu_items[sender]
AttributeError: 'TogaDemo' object has no attribute '_menu_items'
```

## Steps to reproduce

1. Run the toga demo app (`cd toga && python -m toga_demo`)
2. Click on one of the "Commands" > "Action 1"

## Your Environment

* Python 3.6.
* macOS High Sierra
* Toga Target: cocoa

**Comment by clokep** [comment]
A simple fix for this to call `interface._impl`, but that seems incorrect since `_impl` is private?

```diff
diff --git a/src/cocoa/toga_cocoa/app.py b/src/cocoa/toga_cocoa/app.py
--- a/src/cocoa/toga_cocoa/app.py
+++ b/src/cocoa/toga_cocoa/app.py
@@ -70,7 +70,7 @@ class AppDelegate(NSObject):
 
     @objc_method
     def selectMenuItem_(self, sender) -> None:
-        cmd = self.interface._menu_items[sender]
+        cmd = self.interface._impl._menu_items[sender]
         if cmd.action:
             cmd.action(None)
```

If that seems right I'll put up a PR.

**Comment by freakboy3742** [comment]
Your analysis looks right to me, as does the fix. 

`_impl` is private from the perspective of users of the interface; but it's considered fair game if you're already on the implementation layer.
